package com.tjclp.scalagent.macros

import scala.quoted.*
import scala.compiletime.summonInline
import zio.json.*
import zio.json.ast.Json
import com.tjclp.scalagent.config.StructuredOutput

/** Macros for deriving StructuredOutput instances from case classes.
  *
  * Automatically generates JSON Schema and JSON decoder for case classes,
  * with support for @description annotations on fields.
  *
  * Usage:
  * {{{
  * case class Analysis(
  *   @description("A brief summary") summary: String,
  *   @description("Score from 1-10") score: Int,
  *   tags: List[String]
  * ) derives JsonDecoder
  *
  * given StructuredOutput[Analysis] = StructuredOutput.derive[Analysis]
  * }}}
  */
object StructuredOutputMacros:

  /** Derive a StructuredOutput instance for a case class.
    *
    * Generates JSON Schema at compile time and uses summonInline to get
    * the JsonDecoder at the call site. The case class must have a JsonDecoder
    * available (e.g., via `derives JsonDecoder`).
    */
  inline def derive[A]: StructuredOutput[A] =
    // Schema generated by macro, decoder summoned at call site
    createInstance[A](generateSchema[A], summonInline[JsonDecoder[A]])

  /** Helper to create the StructuredOutput instance */
  def createInstance[A](schema: Json, decoder: JsonDecoder[A]): StructuredOutput[A] =
    new StructuredOutput[A]:
      val jsonSchema: Json = schema
      def parse(json: Json): Either[String, A] = json.as[A](using decoder)

  /** Generate JSON Schema at compile time */
  inline def generateSchema[A]: Json = ${ generateSchemaImpl[A] }

  private def generateSchemaImpl[A: Type](using Quotes): Expr[Json] =
    import quotes.reflect.*

    val tpe = TypeRepr.of[A]
    val sym = tpe.typeSymbol

    // Verify it's a case class
    if !sym.flags.is(Flags.Case) then
      report.errorAndAbort(s"StructuredOutput.derive requires a case class, but ${sym.fullName} is not a case class")

    // Get case class fields
    val fields = sym.caseFields

    // Extract field info: (name, type, isOptional, description)
    val fieldInfos = fields.map { field =>
      val fieldName = field.name
      val fieldType = tpe.memberType(field)

      // Check if field is Optional
      val (isOptional, innerType) = fieldType match
        case AppliedType(tycon, List(inner)) if tycon.typeSymbol.fullName == "scala.Option" =>
          (true, inner)
        case other =>
          (false, other)

      // Extract @description annotation
      val descriptionOpt = field.annotations.collectFirst {
        case ann if ann.tpe.typeSymbol.fullName == "com.tjclp.scalagent.macros.description" =>
          ann match
            case Apply(_, List(Literal(StringConstant(text)))) => text
            case _ =>
              report.warning(s"Could not extract description text for field $fieldName")
              ""
      }

      (fieldName, innerType, isOptional, descriptionOpt)
    }

    // Generate JSON Schema expression
    generateSchemaExpr(fieldInfos)

  /** Generate an expression that creates the JSON Schema */
  private def generateSchemaExpr(using Quotes)(
      fieldInfos: List[(String, quotes.reflect.TypeRepr, Boolean, Option[String])]
  ): Expr[Json] =
    import quotes.reflect.*

    // Build properties map
    val propertiesExprs: List[Expr[(String, Json)]] = fieldInfos.map { case (name, tpe, _, descOpt) =>
      val nameExpr = Expr(name)
      val typeSchemaExpr = typeToSchemaExpr(tpe)

      descOpt match
        case Some(desc) =>
          val descExpr = Expr(desc)
          '{ ($nameExpr, addDescription($typeSchemaExpr, $descExpr)) }
        case None =>
          '{ ($nameExpr, $typeSchemaExpr) }
    }

    // Build required array (non-optional fields)
    val requiredExprs: List[Expr[String]] = fieldInfos.collect {
      case (name, _, false, _) => Expr(name)
    }

    val propertiesListExpr = Expr.ofList(propertiesExprs)
    val requiredListExpr = Expr.ofList(requiredExprs)

    '{
      Json.Obj(
        "type" -> Json.Str("object"),
        "properties" -> Json.Obj($propertiesListExpr*),
        "required" -> Json.Arr($requiredListExpr.map(Json.Str(_))*),
        "additionalProperties" -> Json.Bool(false)
      )
    }

  /** Convert a type to its JSON Schema representation */
  private def typeToSchemaExpr(using Quotes)(tpe: quotes.reflect.TypeRepr): Expr[Json] =
    import quotes.reflect.*

    tpe.dealias match
      // String
      case t if t =:= TypeRepr.of[String] =>
        '{ Json.Obj("type" -> Json.Str("string")) }

      // Int
      case t if t =:= TypeRepr.of[Int] =>
        '{ Json.Obj("type" -> Json.Str("integer")) }

      // Long
      case t if t =:= TypeRepr.of[Long] =>
        '{ Json.Obj("type" -> Json.Str("integer"), "format" -> Json.Str("int64")) }

      // Double
      case t if t =:= TypeRepr.of[Double] =>
        '{ Json.Obj("type" -> Json.Str("number"), "format" -> Json.Str("double")) }

      // Float
      case t if t =:= TypeRepr.of[Float] =>
        '{ Json.Obj("type" -> Json.Str("number"), "format" -> Json.Str("float")) }

      // Boolean
      case t if t =:= TypeRepr.of[Boolean] =>
        '{ Json.Obj("type" -> Json.Str("boolean")) }

      // List[T]
      case AppliedType(tycon, List(elemType)) if tycon.typeSymbol.fullName == "scala.collection.immutable.List" =>
        val elemSchemaExpr = typeToSchemaExpr(elemType)
        '{ Json.Obj("type" -> Json.Str("array"), "items" -> $elemSchemaExpr) }

      // Vector[T]
      case AppliedType(tycon, List(elemType)) if tycon.typeSymbol.fullName == "scala.collection.immutable.Vector" =>
        val elemSchemaExpr = typeToSchemaExpr(elemType)
        '{ Json.Obj("type" -> Json.Str("array"), "items" -> $elemSchemaExpr) }

      // Seq[T]
      case AppliedType(tycon, List(elemType)) if tycon.typeSymbol.fullName.contains("Seq") =>
        val elemSchemaExpr = typeToSchemaExpr(elemType)
        '{ Json.Obj("type" -> Json.Str("array"), "items" -> $elemSchemaExpr) }

      // Set[T]
      case AppliedType(tycon, List(elemType)) if tycon.typeSymbol.fullName == "scala.collection.immutable.Set" =>
        val elemSchemaExpr = typeToSchemaExpr(elemType)
        '{ Json.Obj("type" -> Json.Str("array"), "items" -> $elemSchemaExpr, "uniqueItems" -> Json.Bool(true)) }

      // Option[T] - just return the inner type schema
      case AppliedType(tycon, List(inner)) if tycon.typeSymbol.fullName == "scala.Option" =>
        typeToSchemaExpr(inner)

      // Map[String, V]
      case AppliedType(tycon, List(keyType, valueType)) if tycon.typeSymbol.fullName.contains("Map") =>
        val valueSchemaExpr = typeToSchemaExpr(valueType)
        '{ Json.Obj("type" -> Json.Str("object"), "additionalProperties" -> $valueSchemaExpr) }

      // Enum (Scala 3)
      case t if t.typeSymbol.flags.is(Flags.Enum) =>
        val enumCases = t.typeSymbol.children.map(_.name)
        val casesExpr = Expr(enumCases)
        '{ Json.Obj("type" -> Json.Str("string"), "enum" -> Json.Arr($casesExpr.map(Json.Str(_))*)) }

      // Nested case class
      case t if t.typeSymbol.flags.is(Flags.Case) =>
        // Recursively generate schema for nested case class
        val nestedFields = t.typeSymbol.caseFields.map { field =>
          val fieldName = field.name
          val fieldType = t.memberType(field)

          val (isOptional, innerType) = fieldType match
            case AppliedType(tycon, List(inner)) if tycon.typeSymbol.fullName == "scala.Option" =>
              (true, inner)
            case other =>
              (false, other)

          val descOpt = field.annotations.collectFirst {
            case ann if ann.tpe.typeSymbol.fullName == "com.tjclp.scalagent.macros.description" =>
              ann match
                case Apply(_, List(Literal(StringConstant(text)))) => text
                case _ => ""
          }

          (fieldName, innerType, isOptional, descOpt)
        }
        generateSchemaExpr(nestedFields)

      // Default fallback
      case other =>
        report.warning(s"Unknown type ${other.show}, using string schema")
        '{ Json.Obj("type" -> Json.Str("string")) }

  /** Add description field to a JSON Schema */
  def addDescription(schema: Json, description: String): Json =
    schema match
      case Json.Obj(fields) =>
        Json.Obj(fields.toList :+ ("description" -> Json.Str(description))*)
      case other => other
