package com.tjclp.scalagent.macros

import scala.quoted.*
import scala.compiletime.summonInline
import com.tjclp.scalagent.macros.SchemaMacroSupport.*
import zio.json.*
import zio.json.ast.Json
import com.tjclp.scalagent.config.StructuredOutput
import com.tjclp.scalagent.schema.JsonSchemaAst

/** Macros for deriving StructuredOutput instances from case classes.
  *
  * Automatically generates JSON Schema and JSON decoder for case classes,
  * with support for @description annotations on fields.
  *
  * Usage:
  * {{{
  * case class Analysis(
  *   @description("A brief summary") summary: String,
  *   @description("Score from 1-10") score: Int,
  *   tags: List[String]
  * ) derives JsonDecoder
  *
  * given StructuredOutput[Analysis] = StructuredOutput.derive[Analysis]
  * }}}
  */
object StructuredOutputMacros:

  /** Derive a StructuredOutput instance for a case class.
    *
    * Generates JSON Schema at compile time and uses summonInline to get
    * the JsonDecoder at the call site. The case class must have a JsonDecoder
    * available (e.g., via `derives JsonDecoder`).
    */
  inline def derive[A]: StructuredOutput[A] =
    // Schema generated by macro, decoder summoned at call site
    createInstance[A](generateSchema[A], summonInline[JsonDecoder[A]])

  /** Helper to create the StructuredOutput instance */
  def createInstance[A](schema: Json, decoder: JsonDecoder[A]): StructuredOutput[A] =
    new StructuredOutput[A]:
      val jsonSchema: Json = schema
      def parse(json: Json): Either[String, A] = json.as[A](using decoder)

  /** Generate JSON Schema at compile time */
  inline def generateSchema[A]: Json = ${ generateSchemaImpl[A] }

  private def generateSchemaImpl[A: Type](using Quotes): Expr[Json] =
    import quotes.reflect.*

    val tpe = TypeRepr.of[A]
    val sym = tpe.typeSymbol

    // Verify it's a case class
    if !sym.flags.is(Flags.Case) then
      report.errorAndAbort(s"StructuredOutput.derive requires a case class, but ${sym.fullName} is not a case class")

    val fieldInfos = caseClassFieldInfos(tpe)

    // Generate JSON Schema expression
    generateSchemaExpr(fieldInfos)

  /** Generate an expression that creates the JSON Schema */
  private def generateSchemaExpr(using Quotes)(
      fieldInfos: List[(String, quotes.reflect.TypeRepr, Boolean, Option[String])]
  ): Expr[Json] =
    import quotes.reflect.*

    // Build properties map
    val propertiesExprs: List[Expr[(String, Json)]] = fieldInfos.map { case (name, tpe, _, descOpt) =>
      val nameExpr = Expr(name)
      val typeSchemaExpr = typeToSchemaExpr(tpe)

      descOpt match
        case Some(desc) =>
          val descExpr = Expr(desc)
          '{ ($nameExpr, addDescription($typeSchemaExpr, $descExpr)) }
        case None =>
          '{ ($nameExpr, $typeSchemaExpr) }
    }

    // Build required array (non-optional fields)
    val requiredExprs: List[Expr[String]] = fieldInfos.collect {
      case (name, _, false, _) => Expr(name)
    }

    val propertiesListExpr = Expr.ofList(propertiesExprs)
    val requiredListExpr = Expr.ofList(requiredExprs)

    '{ JsonSchemaAst.objectSchema($propertiesListExpr, $requiredListExpr) }

  /** Convert a type to its JSON Schema representation */
  private def typeToSchemaExpr(using Quotes)(tpe: quotes.reflect.TypeRepr): Expr[Json] =
    import quotes.reflect.*

    tpe.dealias match
      // String
      case t if t =:= TypeRepr.of[String] =>
        '{ JsonSchemaAst.string }

      // Int
      case t if t =:= TypeRepr.of[Int] =>
        '{ JsonSchemaAst.integer }

      // Long
      case t if t =:= TypeRepr.of[Long] =>
        '{ JsonSchemaAst.integerWithFormat("int64") }

      // Double — use plain "number" (Agent SDK doesn't support format:"double")
      case t if t =:= TypeRepr.of[Double] =>
        '{ JsonSchemaAst.number }

      // Float — use plain "number" (Agent SDK doesn't support format:"float")
      case t if t =:= TypeRepr.of[Float] =>
        '{ JsonSchemaAst.number }

      // Boolean
      case t if t =:= TypeRepr.of[Boolean] =>
        '{ JsonSchemaAst.boolean }

      // List/Vector/Seq/Set
      case AppliedType(tycon, List(elemType)) if isListLike(tycon) =>
        val elemSchemaExpr = typeToSchemaExpr(elemType)
        if isSetLike(tycon) then
          '{ JsonSchemaAst.array(items = $elemSchemaExpr, uniqueItems = true) }
        else
          '{ JsonSchemaAst.array($elemSchemaExpr) }

      // Option[T] - just return the inner type schema
      case AppliedType(tycon, List(inner)) if tycon.typeSymbol.fullName == "scala.Option" =>
        typeToSchemaExpr(inner)

      // Map[String, V]
      case AppliedType(tycon, List(_, valueType)) if isMapLike(tycon) =>
        val valueSchemaExpr = typeToSchemaExpr(valueType)
        '{ JsonSchemaAst.map($valueSchemaExpr) }

      // Either[L, R]
      case AppliedType(tycon, List(leftType, rightType)) if isEitherLike(tycon) =>
        val leftSchemaExpr = typeToSchemaExpr(leftType)
        val rightSchemaExpr = typeToSchemaExpr(rightType)
        '{ JsonSchemaAst.oneOf(List($leftSchemaExpr, $rightSchemaExpr)) }

      // Tuple2[A, B]
      case AppliedType(tycon, List(leftType, rightType)) if isTuple2Like(tycon) =>
        val leftSchemaExpr = typeToSchemaExpr(leftType)
        val rightSchemaExpr = typeToSchemaExpr(rightType)
        '{ JsonSchemaAst.tuple2($leftSchemaExpr, $rightSchemaExpr) }

      // Enum (Scala 3)
      case t if t.typeSymbol.flags.is(Flags.Enum) =>
        val enumCases = enumCaseNames(t)
        val casesExpr = Expr.ofList(enumCases.map(Expr(_)))
        '{ JsonSchemaAst.enumOf($casesExpr) }

      // Nested case class
      case t if t.typeSymbol.flags.is(Flags.Case) =>
        generateSchemaExpr(caseClassFieldInfos(t))

      // Default fallback
      case other =>
        report.warning(s"Unknown type ${other.show}, using string schema")
        '{ JsonSchemaAst.string }

  /** Add description field to a JSON Schema */
  def addDescription(schema: Json, description: String): Json =
    JsonSchemaAst.withDescription(schema, description)
